
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/TheThingsNetwork/api"

[[constraint]]
  branch = "master"
  name = "github.com/TheThingsNetwork/go-account-lib"

[[constraint]]
  branch = "master"
  name = "github.com/TheThingsNetwork/go-utils"

[[constraint]]
  name = "github.com/TheThingsNetwork/ttn"
  version = "2.8.1"

[[constraint]]
  branch = "master"
  name = "github.com/brocaar/lorawan"

[[constraint]]
  branch = "master"
  name = "github.com/eclipse/paho.mqtt.golang"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[override]]
  branch = "master"
  name = "github.com/grpc-ecosystem/grpc-gateway"
